import type {
  DashboardSummary,
  DocumentView,
  ItemView,
  NotificationView,
  ObligationView,
  TimelineEntry,
} from "./types";
import type { ActiveHousehold, Viewer } from "@/providers/household-provider";

/**
 * Development fixtures.
 *
 * A caregiver household — the PRD wedge — with realistic administrative mess: a
 * parent's Medicare enrollment window, a lapsing registration, a deposit nobody
 * remembers, a document mid-review. Fixtures are shaped exactly like API responses
 * so the screens that consume them need zero changes when the transport switches
 * from this module to `/v1` (Phase 2D).
 *
 * Dates are generated relative to `now` so the demo never rots into "everything is
 * overdue by three years".
 */

const now = new Date();
const day = 86_400_000;
const iso = (offsetDays: number) => new Date(now.getTime() + offsetDays * day).toISOString();
const date = (offsetDays: number) => iso(offsetDays).slice(0, 10);

export const VIEWER: Viewer = {
  id: "0192f5a1-0000-7000-8000-000000000001",
  displayName: "Dana Reyes",
  email: "dana@example.com",
};

export const HOUSEHOLD: ActiveHousehold = {
  id: "0192f5a1-0000-7000-8000-0000000000a1",
  name: "The Reyes Household",
  role: "owner",
  timezone: "America/New_York",
  locale: "en-US",
  emailAlias: "h-4kq7x@in.autobureau.com",
  plan: "free",
  members: [
    { id: "m-1", displayName: "Dana Reyes", kind: "adult" },
    { id: "m-2", displayName: "Elena Reyes", kind: "dependent" },
    { id: "m-3", displayName: "Mateo Reyes", kind: "child" },
  ],
};

const memberName = (id: string | null) =>
  HOUSEHOLD.members.find((m) => m.id === id)?.displayName ?? null;

export const OBLIGATIONS: ObligationView[] = [
  {
    id: "o-1",
    household_id: HOUSEHOLD.id,
    item_id: "i-2",
    member_id: "m-2",
    title: "Elena's Medicare Part B enrollment window closes",
    kind: "enrollment",
    direction: "owed_by_household",
    status: "action_needed",
    priority: 1,
    due_at: iso(9),
    window_start: iso(-60),
    grace_until: null,
    amount_cents: null,
    currency: null,
    recurrence: null,
    source: "ai",
    source_document_id: "d-2",
    ai_confidence: 0.94,
    outcome: null,
    verified_at: iso(-12),
    member_name: memberName("m-2"),
    item_name: "Medicare — Elena",
    provenance: {
      document_id: "d-2",
      document_title: "Medicare enrollment notice",
      excerpt: "General Enrollment Period ends…",
      captured_at: iso(-12),
    },
    days_until: 9,
  },
  {
    id: "o-2",
    household_id: HOUSEHOLD.id,
    item_id: "i-1",
    member_id: "m-1",
    title: "Renew vehicle registration — Honda CR-V",
    kind: "renewal",
    direction: "owed_by_household",
    status: "action_needed",
    priority: 1,
    due_at: iso(21),
    window_start: iso(-9),
    grace_until: iso(51),
    amount_cents: 16_800,
    currency: "USD",
    recurrence: "FREQ=YEARLY",
    source: "system",
    source_document_id: "d-1",
    ai_confidence: null,
    outcome: null,
    verified_at: iso(-30),
    member_name: memberName("m-1"),
    item_name: "Honda CR-V registration",
    provenance: {
      document_id: "d-1",
      document_title: "DMV renewal notice",
      captured_at: iso(-30),
    },
    days_until: 21,
  },
  {
    id: "o-3",
    household_id: HOUSEHOLD.id,
    item_id: "i-4",
    member_id: null,
    title: "Security deposit refund from Oakline Apartments",
    kind: "claim",
    direction: "owed_to_household",
    status: "upcoming",
    priority: 2,
    due_at: iso(34),
    window_start: null,
    grace_until: null,
    amount_cents: 180_000,
    currency: "USD",
    recurrence: null,
    source: "ai",
    source_document_id: "d-3",
    ai_confidence: 0.88,
    outcome: null,
    verified_at: iso(-4),
    member_name: null,
    item_name: "Oakline Apartments lease",
    provenance: {
      document_id: "d-3",
      document_title: "Lease agreement — Oakline",
      excerpt: "Security deposit of $1,800 refundable within 30 days of vacating…",
      captured_at: iso(-4),
    },
    days_until: 34,
  },
  {
    id: "o-4",
    household_id: HOUSEHOLD.id,
    item_id: "i-3",
    member_id: "m-2",
    title: "Elena's supplemental insurance premium",
    kind: "payment",
    direction: "owed_by_household",
    status: "upcoming",
    priority: 2,
    due_at: iso(6),
    window_start: null,
    grace_until: iso(16),
    amount_cents: 21_450,
    currency: "USD",
    recurrence: "FREQ=MONTHLY",
    source: "ai",
    source_document_id: "d-4",
    ai_confidence: 0.97,
    outcome: null,
    verified_at: iso(-2),
    member_name: memberName("m-2"),
    item_name: "Mutual of Omaha supplemental",
    provenance: {
      document_id: "d-4",
      document_title: "Premium statement — August",
      captured_at: iso(-2),
    },
    days_until: 6,
  },
  {
    id: "o-5",
    household_id: HOUSEHOLD.id,
    item_id: "i-5",
    member_id: "m-1",
    title: "Cancel before the free trial converts — Streamly",
    kind: "cancellation_window",
    direction: "owed_by_household",
    status: "action_needed",
    priority: 3,
    due_at: iso(2),
    window_start: iso(-12),
    grace_until: null,
    amount_cents: 1_499,
    currency: "USD",
    recurrence: null,
    source: "ai",
    source_document_id: "d-5",
    ai_confidence: 0.91,
    outcome: null,
    verified_at: iso(-12),
    member_name: memberName("m-1"),
    item_name: "Streamly subscription",
    provenance: {
      document_id: "d-5",
      document_title: "Streamly welcome email",
      captured_at: iso(-12),
    },
    days_until: 2,
  },
  {
    id: "o-6",
    household_id: HOUSEHOLD.id,
    item_id: "i-6",
    member_id: "m-3",
    title: "Mateo's passport renewal",
    kind: "renewal",
    direction: "owed_by_household",
    status: "upcoming",
    priority: 2,
    due_at: iso(147),
    window_start: iso(-33),
    grace_until: null,
    amount_cents: 13_500,
    currency: "USD",
    recurrence: null,
    source: "system",
    source_document_id: null,
    ai_confidence: null,
    outcome: null,
    verified_at: iso(-45),
    member_name: memberName("m-3"),
    item_name: "Passport — Mateo",
    provenance: null,
    days_until: 147,
  },
  {
    id: "o-7",
    household_id: HOUSEHOLD.id,
    item_id: "i-7",
    member_id: null,
    title: "Washing machine warranty claim window",
    kind: "claim",
    direction: "owed_to_household",
    status: "done",
    priority: 3,
    due_at: iso(-8),
    window_start: null,
    grace_until: null,
    amount_cents: 42_000,
    currency: "USD",
    recurrence: null,
    source: "ai",
    source_document_id: "d-6",
    ai_confidence: 0.86,
    outcome: { done_via: "action_kit", cost_cents: 0, process_matched: true },
    verified_at: iso(-8),
    member_name: null,
    item_name: "LG washer warranty",
    provenance: {
      document_id: "d-6",
      document_title: "LG purchase receipt",
      captured_at: iso(-60),
    },
    days_until: -8,
  },
];

export const ITEMS: ItemView[] = [
  {
    id: "i-1",
    household_id: HOUSEHOLD.id,
    member_id: "m-1",
    kind: "vehicle_registration",
    name: "Honda CR-V registration",
    status: "expiring",
    vendor_id: null,
    vendor_name: "NY DMV",
    amount_cents: 16_800,
    currency: "USD",
    billing_cycle: "yearly",
    valid_from: date(-344),
    expires_at: date(21),
    verified_at: iso(-30),
    source_document_id: "d-1",
    member_name: "Dana Reyes",
    open_obligation_count: 1,
    document_count: 2,
    secrets: [{ field: "plate", last4: "8241" }],
  },
  {
    id: "i-2",
    household_id: HOUSEHOLD.id,
    member_id: "m-2",
    kind: "benefit_plan",
    name: "Medicare — Elena",
    status: "active",
    vendor_id: null,
    vendor_name: "Medicare",
    amount_cents: null,
    currency: null,
    billing_cycle: null,
    valid_from: date(-400),
    expires_at: null,
    verified_at: iso(-12),
    source_document_id: "d-2",
    member_name: "Elena Reyes",
    open_obligation_count: 1,
    document_count: 3,
    secrets: [{ field: "member_id", last4: "5512" }],
  },
  {
    id: "i-3",
    household_id: HOUSEHOLD.id,
    member_id: "m-2",
    kind: "insurance_policy",
    name: "Mutual of Omaha supplemental",
    status: "active",
    vendor_id: null,
    vendor_name: "Mutual of Omaha",
    amount_cents: 21_450,
    currency: "USD",
    billing_cycle: "monthly",
    valid_from: date(-210),
    expires_at: date(155),
    verified_at: iso(-2),
    source_document_id: "d-4",
    member_name: "Elena Reyes",
    open_obligation_count: 1,
    document_count: 4,
    secrets: [{ field: "policy_number", last4: "9037" }],
  },
  {
    id: "i-4",
    household_id: HOUSEHOLD.id,
    member_id: null,
    kind: "lease",
    name: "Oakline Apartments lease",
    status: "active",
    vendor_id: null,
    vendor_name: "Oakline Property Group",
    amount_cents: 235_000,
    currency: "USD",
    billing_cycle: "monthly",
    valid_from: date(-320),
    expires_at: date(34),
    verified_at: iso(-4),
    source_document_id: "d-3",
    member_name: null,
    open_obligation_count: 1,
    document_count: 1,
    secrets: [],
  },
  {
    id: "i-5",
    household_id: HOUSEHOLD.id,
    member_id: "m-1",
    kind: "subscription",
    name: "Streamly",
    status: "active",
    vendor_id: null,
    vendor_name: "Streamly",
    amount_cents: 1_499,
    currency: "USD",
    billing_cycle: "monthly",
    valid_from: date(-12),
    expires_at: null,
    verified_at: iso(-12),
    source_document_id: "d-5",
    member_name: "Dana Reyes",
    open_obligation_count: 1,
    document_count: 1,
    secrets: [],
  },
  {
    id: "i-6",
    household_id: HOUSEHOLD.id,
    member_id: "m-3",
    kind: "passport",
    name: "Passport — Mateo",
    status: "active",
    vendor_id: null,
    vendor_name: "US Department of State",
    amount_cents: null,
    currency: null,
    billing_cycle: null,
    valid_from: date(-1500),
    expires_at: date(147),
    verified_at: iso(-45),
    source_document_id: null,
    member_name: "Mateo Reyes",
    open_obligation_count: 1,
    document_count: 0,
    secrets: [{ field: "passport_number", last4: "6620" }],
  },
  {
    id: "i-7",
    household_id: HOUSEHOLD.id,
    member_id: null,
    kind: "warranty",
    name: "LG washer warranty",
    status: "active",
    vendor_id: null,
    vendor_name: "LG Electronics",
    amount_cents: null,
    currency: null,
    billing_cycle: null,
    valid_from: date(-380),
    expires_at: date(350),
    verified_at: iso(-8),
    source_document_id: "d-6",
    member_name: null,
    open_obligation_count: 0,
    document_count: 1,
    secrets: [],
  },
];

export const DOCUMENTS: DocumentView[] = [
  {
    id: "d-7",
    household_id: HOUSEHOLD.id,
    source: "email",
    status: "needs_review",
    doc_type: "insurance_policy",
    confidence: 0.71,
    title: "Renewal notice — auto policy",
    doc_date: date(-1),
    mime_type: "application/pdf",
    size_bytes: 284_112,
    created_at: iso(-1),
    processed_at: iso(-1),
    member_name: "Dana Reyes",
    linked_item_ids: [],
    proposed_changes: [
      {
        kind: "item",
        action: "update",
        label: "Auto policy — premium and renewal date",
        fields: [
          { path: "amount_cents", value: "$142.30 / month", confidence: 0.93 },
          { path: "expires_at", value: date(58), confidence: 0.71 },
          { path: "vendor_name", value: "Griffin Mutual", confidence: 0.97 },
        ],
      },
      {
        kind: "obligation",
        action: "create",
        label: "Renew auto policy",
        fields: [{ path: "due_at", value: date(58), confidence: 0.71 }],
      },
    ],
  },
  {
    id: "d-2",
    household_id: HOUSEHOLD.id,
    source: "upload",
    status: "processed",
    doc_type: "government_id",
    confidence: 0.96,
    title: "Medicare enrollment notice",
    doc_date: date(-12),
    mime_type: "application/pdf",
    size_bytes: 512_004,
    created_at: iso(-12),
    processed_at: iso(-12),
    member_name: "Elena Reyes",
    linked_item_ids: ["i-2"],
    proposed_changes: null,
  },
  {
    id: "d-4",
    household_id: HOUSEHOLD.id,
    source: "email",
    status: "processed",
    doc_type: "insurance_policy",
    confidence: 0.97,
    title: "Premium statement — August",
    doc_date: date(-2),
    mime_type: "application/pdf",
    size_bytes: 98_233,
    created_at: iso(-2),
    processed_at: iso(-2),
    member_name: "Elena Reyes",
    linked_item_ids: ["i-3"],
    proposed_changes: null,
  },
  {
    id: "d-3",
    household_id: HOUSEHOLD.id,
    source: "upload",
    status: "processed",
    doc_type: "lease",
    confidence: 0.89,
    title: "Lease agreement — Oakline",
    doc_date: date(-320),
    mime_type: "application/pdf",
    size_bytes: 1_204_882,
    created_at: iso(-4),
    processed_at: iso(-4),
    member_name: null,
    linked_item_ids: ["i-4"],
    proposed_changes: null,
  },
  {
    id: "d-1",
    household_id: HOUSEHOLD.id,
    source: "email",
    status: "processed",
    doc_type: "vehicle_registration",
    confidence: 0.99,
    title: "DMV renewal notice",
    doc_date: date(-30),
    mime_type: "application/pdf",
    size_bytes: 176_400,
    created_at: iso(-30),
    processed_at: iso(-30),
    member_name: "Dana Reyes",
    linked_item_ids: ["i-1"],
    proposed_changes: null,
  },
  {
    id: "d-8",
    household_id: HOUSEHOLD.id,
    source: "upload",
    status: "processing",
    doc_type: null,
    confidence: null,
    title: "Scan 2026-08-14",
    doc_date: null,
    mime_type: "image/jpeg",
    size_bytes: 2_881_022,
    created_at: iso(0),
    processed_at: null,
    member_name: null,
    linked_item_ids: [],
    proposed_changes: null,
  },
];

export const TIMELINE: TimelineEntry[] = [
  {
    id: "t-1",
    at: iso(-1),
    kind: "document_added",
    title: "Renewal notice — auto policy",
    detail: "Arrived by email · needs your review",
    href: "/documents/d-7",
  },
  {
    id: "t-2",
    at: iso(-2),
    kind: "obligation_created",
    title: "Elena's supplemental insurance premium",
    detail: "From the August premium statement",
    member_name: "Elena Reyes",
    href: "/obligations/o-4",
  },
  {
    id: "t-3",
    at: iso(-4),
    kind: "value_found",
    title: "Security deposit found in your lease",
    detail: "Refundable within 30 days of moving out",
    amount_cents: 180_000,
    href: "/obligations/o-3",
  },
  {
    id: "t-4",
    at: iso(-8),
    kind: "obligation_completed",
    title: "Washing machine warranty claim filed",
    detail: "Repair covered in full",
    amount_cents: 42_000,
  },
  {
    id: "t-5",
    at: iso(-12),
    kind: "item_added",
    title: "Medicare — Elena",
    detail: "From the enrollment notice you uploaded",
    member_name: "Elena Reyes",
    href: "/household/i-2",
  },
  {
    id: "t-6",
    at: iso(-21),
    kind: "reminder_sent",
    title: "Reminder: vehicle registration renewal",
    detail: "30 days before due",
  },
];

export const NOTIFICATIONS: NotificationView[] = [
  {
    id: "n-1",
    kind: "document.needs_review",
    title: "A document needs your review",
    body: "We read the auto policy renewal notice but weren't confident about the renewal date.",
    created_at: iso(-1),
    read_at: null,
    href: "/documents/d-7",
  },
  {
    id: "n-2",
    kind: "obligation.due_soon",
    title: "Streamly trial converts in 2 days",
    body: "Cancel before Thursday to avoid the $14.99 monthly charge.",
    created_at: iso(-1),
    read_at: null,
    href: "/obligations/o-5",
  },
  {
    id: "n-3",
    kind: "obligation.due_soon",
    title: "Elena's Medicare window closes in 9 days",
    body: "Missing this window delays coverage by up to a year.",
    created_at: iso(-3),
    read_at: iso(-2),
    href: "/obligations/o-1",
  },
  {
    id: "n-4",
    kind: "digest.weekly",
    title: "Your week: 2 need attention, 3 handled",
    body: "Nothing is at risk in the next 7 days.",
    created_at: iso(-6),
    read_at: iso(-6),
    href: "/dashboard",
  },
];

export const SUMMARY: DashboardSummary = {
  action_needed: OBLIGATIONS.filter((o) => o.status === "action_needed").length,
  upcoming_30d: OBLIGATIONS.filter(
    (o) => o.days_until >= 0 && o.days_until <= 30 && o.status !== "done",
  ).length,
  needs_review: DOCUMENTS.filter((d) => d.status === "needs_review").length,
  items_tracked: ITEMS.length,
  value_found_cents: 222_000,
  coverage: { captured: 7, expected: 11 },
  next_digest_at: iso(3),
};
